spring.application.name=smartcampus
server.port=8081

spring.data.mongodb.uri=${MONGODB_URI}

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.deserialization.fail-on-unknown-properties=false